export const data = [
    {
        question: "Bir web sayfasında metinleri biçimlendirmek için kullanılan dildir?",
        option1: "HTML",
        option2: "CSS",
        option3: "JavaScript",
        option4: "Python",
        ans: 2,
    },
    {
        question: "Bir sayfanın en üstünde bulunan, kullanıcıları belirli bir konuya yönlendiren metindir?",
        option1: "Header",
        option2: "Footer",
        option3: "Link",
        option4: "Paragraph",
        ans: 1,
    },
    {
        question: "Bir cihazın ne kadar hızlı işlem yapabildiğini belirleyen bileşendir?",
        option1: "RAM",
        option2: "CPU",
        option3: "Hard Disk",
        option4: "GPU",
        ans: 2,
    },
    {
        question: "Bir bilgisayarın belleğine dışarıdan erişilemez?",
        option1: "ROM",
        option2: "RAM",
        option3: "CPU",
        option4: "GPU",
        ans: 1,
    },
    {
        question: "Hangisi bir bilgisayar virüsü türü değildir?",
        option1: "Trojan",
        option2: "Spyware",
        option3: "Firewall",
        option4: "Worm",
        ans: 3,
    },
    {
        question: "Hangi programlama dili web tarayıcılarında doğrudan çalışabilir?",
        option1: "Python",
        option2: "Java",
        option3: "JavaScript",
        option4: "C++",
        ans: 3,
    },
    {
        question: "Bir bilgisayarın sabit diskindeki veriler nerede saklanır?",
        option1: "RAM",
        option2: "ROM",
        option3: "SSD",
        option4: "CPU",
        ans: 3,
    },
    {
        question: "Hangisi bir CSS özellikleri dosyasıdır?",
        option1: ".html",
        option2: ".css",
        option3: ".js",
        option4: ".php",
        ans: 2,
    },
    {
        question: "Hangisi bir veri tabanı modelleme tekniği değildir?",
        option1: "Relational",
        option2: "NoSQL",
        option3: "Object-Oriented",
        option4: "Binary",
        ans: 4,
    },
    {
        question: "Hangisi bir yazılım geliştirme dili değildir?",
        option1: "Ruby",
        option2: "C#",
        option3: "Visual Basic",
        option4: "Adobe Photoshop",
        ans: 4,
    },
    {
        question: "Bir bilgisayarın bağlantı noktalarını kontrol eden bileşen hangisidir?",
        option1: "CPU",
        option2: "GPU",
        option3: "Motherboard",
        option4: "Network Interface Card",
        ans: 4,
    },
    {
        question: "Bir web sitesinin mobil cihazlarda uyumlu olması için kullanılan teknik hangisidir?",
        option1: "Responsive Design",
        option2: "JavaScript",
        option3: "PHP",
        option4: "Ajax",
        ans: 1,
    },
    {
        question: "Hangisi bir Linux dağıtımı değildir?",
        option1: "Ubuntu",
        option2: "Fedora",
        option3: "CentOS",
        option4: "Windows",
        ans: 4,
    },
    {
        question: "Hangisi bir mobil işletim sistemi değildir?",
        option1: "Android",
        option2: "iOS",
        option3: "Windows",
        option4: "Ubuntu",
        ans: 4,
    },
    {
        question: "Hangisi bir programlama paradigmasıdır?",
        option1: "Backtracking",
        option2: "Brute Force",
        option3: "Divide and Conquer",
        option4: "Greedy",
        ans: 1,
    },
    {
        question: "Hangisi bir veri yapıları türüdür?",
        option1: "Binary Tree",
        option2: "Double Loop",
        option3: "Circular Array",
        option4: "Parallel Function",
        ans: 1,
    },
    {
        question: "Hangisi bir metin düzenleyici programıdır?",
        option1: "Microsoft Word",
        option2: "Adobe Photoshop",
        option3: "Microsoft Excel",
        option4: "Adobe Illustrator",
        ans: 1,
    },
    {
        question: "Hangisi bir web sunucusu yazılımıdır?",
        option1: "Apache",
        option2: "MySQL",
        option3: "Ubuntu",
        option4: "MongoDB",
        ans: 1,
    },
    {
        question: "Bir web sayfasında birden fazla sayfaya bağlantı vermek için kullanılan etiket hangisidir?",
        option1: "<a>",
        option2: "<p>",
        option3: "<h1>",
        option4: "<div>",
        ans: 1,
    },
    {
        question: "Hangisi bir yazılım geliştirme modeli değildir?",
        option1: "Agile",
        option2: "Waterfall",
        option3: "Scrum",
        option4: "ASCII",
        ans: 4,
    },
    {
        question: "İnternet bağlantısı için hangi cihaz gereklidir?",
        option1: "Modem",
        option2: "Router",
        option3: "LAN Kablosu",
        option4: "Pen Sürücüsü",
        ans: 1,
    },
    {
        question: "Hangi kıtada en fazla ülke var?",
        option1: "Asya",
        option2: "Avrupa",
        option3: "Kuzey Amerika",
        option4: "Afrika",
        ans: 4,
    },
    {
        question: "Önemsiz e-posta da denir?",
        option1: "Spam",
        option2: "Fake",
        option3: "Arşivlenmiş",
        option4: "Çöp",
        ans: 1,
    },
    {
        question: "Bir bilgisayar aşağıdaki özelliklere sahip değilse BOOT yapamaz?",
        option1: "Application Software",
        option2: "Internet",
        option3: "Operating System",
        option4: "Mouse",
        ans: 3,
    },
    {
        question: "Web sitesinin ilk sayfasına ne ad verilir?",
        option1: "Index Page",
        option2: "Homepage",
        option3: "Sitemap",
        option4: "Pen Drive",
        ans: 2,
    },
    {
        question: "Bilgisayarın beyni olarak da adlandırılan bileşen hangisidir?",
        option1: "CPU",
        option2: "RAM",
        option3: "GPU",
        option4: "Hard Disk",
        ans: 1,
    },
    {
        question: "Hangisi bir programlama dilidir?",
        option1: "HTML",
        option2: "JPEG",
        option3: "XML",
        option4: "PDF",
        ans: 1,
    },
    {
        question: "Hangisi bir web tarayıcısı değildir?",
        option1: "Chrome",
        option2: "Firefox",
        option3: "Safari",
        option4: "Android",
        ans: 4,
    },

    {
        question: "Hangisi bir veri depolama birimi değildir?",
        option1: "Byte",
        option2: "Terabyte",
        option3: "Kilobyte",
        option4: "Hertz",
        ans: 4,
    },
    {
        question: "Hangisi bir sunucu işletim sistemi değildir?",
        option1: "Windows Server",
        option2: "Linux",
        option3: "Ubuntu",
        option4: "iOS",
        ans: 4,
    },
    {
        question: "Hangisi bir veri tabanı yönetim sistemidir?",
        option1: "MySQL",
        option2: "Node.js",
        option3: "React",
        option4: "Angular",
        ans: 1,
    },
    {
        question: "Hangisi bir dosya sıkıştırma formatıdır?",
        option1: ".zip",
        option2: ".rar",
        option3: ".tar",
        option4: ".png",
        ans: 1,
    },
    {
        question: "Hangisi bir veri yapıları türü değildir?",
        option1: "Array",
        option2: "Queue",
        option3: "Tree",
        option4: "Loop",
        ans: 4,
    },
    {
        question: "Bir bilgisayarın çalışmasını sağlayan yazılım hangisidir?",
        option1: "Application Software",
        option2: "Operating System",
        option3: "Driver",
        option4: "Firmware",
        ans: 2,
    },
    {
        question: "Bir sayfanın en altında bulunan, genellikle iletişim bilgilerini içeren kısımdır?",
        option1: "Header",
        option2: "Footer",
        option3: "Sidebar",
        option4: "Body",
        ans: 2,
    },
    {
        question: "Hangisi bir veri tabanı yönetim sistemidir?",
        option1: "MongoDB",
        option2: "Express.js",
        option3: "React",
        option4: "Node.js",
        ans: 1,
    },
    {
        question: "Hangisi bir CSS ön işleyici değildir?",
        option1: "Sass",
        option2: "Less",
        option3: "JavaScript",
        option4: "Stylus",
        ans: 3,
    },
    {
        question: "Hangisi bir döngü kontrol yapısıdır?",
        option1: "if-else",
        option2: "for",
        option3: "switch-case",
        option4: "try-catch",
        ans: 2,
    },
    {
        question: "Bir bilgisayarın güç kaynağına takılan cihaz hangisidir?",
        option1: "Keyboard",
        option2: "Mouse",
        option3: "Monitor",
        option4: "UPS",
        ans: 4,
    },
    {
        question: "Hangisi bir veri tabanı dilidir?",
        option1: "HTML",
        option2: "CSS",
        option3: "SQL",
        option4: "JavaScript",
        ans: 3,
    },
    {
        question: "Hangisi bir web tabanlı dosya paylaşım hizmetidir?",
        option1: "Google Drive",
        option2: "Microsoft Word",
        option3: "Adobe Acrobat",
        option4: "Notepad",
        ans: 1,
    },
    {
        question: "Hangisi bir döngü yapısal kontrol yapısıdır?",
        option1: "if-else",
        option2: "for",
        option3: "switch-case",
        option4: "try-catch",
        ans: 2,
    },
    {
        question: "Hangisi bir JavaScript kütüphanesi değildir?",
        option1: "React",
        option2: "jQuery",
        option3: "Bootstrap",
        option4: "Angular",
        ans: 4,
    },
    {
        question: "Hangisi bir kodlama platformudur?",
        option1: "GitHub",
        option2: "Trello",
        option3: "Slack",
        option4: "Figma",
        ans: 1,
    },
    {
        question: "Hangisi bir veri tabanı türüdür?",
        option1: "HTML",
        option2: "CSS",
        option3: "SQLite",
        option4: "JavaScript",
        ans: 3,
    },
    {
        question: "Bir bilgisayar ağına bağlanmak için hangi cihaz kullanılır?",
        option1: "Router",
        option2: "Printer",
        option3: "Monitor",
        option4: "Keyboard",
        ans: 1,
    },
    {
        question: "Hangisi bir internet tarayıcısı değildir?",
        option1: "Google Chrome",
        option2: "Firefox",
        option3: "Safari",
        option4: "Windows",
        ans: 4,
    },
    {
        question: "Bir bilgisayarın çalışması için hangi bileşen gerekli değildir?",
        option1: "CPU",
        option2: "RAM",
        option3: "Hard Disk",
        option4: "Mouse",
        ans: 4,
    },
    {
        question: "Bir bilgisayarın ekranını yazılım olarak görüntüleyen bileşen hangisidir?",
        option1: "Monitor",
        option2: "Keyboard",
        option3: "Mouse",
        option4: "Graphics Card",
        ans: 1,
    },
    {
        question: "Hangisi bir işletim sistemidir?",
        option1: "Microsoft Office",
        option2: "Linux",
        option3: "Adobe Photoshop",
        option4: "Google Chrome",
        ans: 2,
    },
    {
        question: "Bir bilgisayarın fiziksel parçalarının tümünü içeren kutuya ne ad verilir?",
        option1: "Monitor",
        option2: "Keyboard",
        option3: "Mouse",
        option4: "Tower",
        ans: 4,
    },
    {
        question: "Hangisi bir programlama dili değildir?",
        option1: "Python",
        option2: "HTML",
        option3: "JavaScript",
        option4: "Java",
        ans: 2,
    },
    {
        question: "Hangisi bir dosya uzantısıdır?",
        option1: ".mp4",
        option2: ".mp3",
        option3: ".exe",
        option4: ".avi",
        ans: 1,
    },
    {
        question: "Hangisi bir sayfa yönlendirme etiketidir?",
        option1: "<a>",
        option2: "<p>",
        option3: "<div>",
        option4: "<span>",
        ans: 1,
    },


];